services:
    - type: web
      name: trevo
      env: static
      buildCommand: npm run build
      staticPublishPath: ./dist/trevo
      routes:
          - type: rewrite
            source: /*
            destination: /index.html
